{"name": "Test login with invalid accounts", "status": "passed", "parameters": [{"name": "account", "value": "<data_object.account.Account object at 0x00000205A6136A50>"}], "start": 1702398260124, "stop": 1702398265789, "uuid": "b96a45b6-0c78-41e7-af99-70310684e51e", "historyId": "16aa2731f7a468fc83caff4a1e438674", "testCaseId": "1b1f20a980acb2adddf0d9d9639eb7fe", "fullName": "testcases.ui.test_login#test_login_unsuccessfully_with_valid_account", "labels": [{"name": "parentSuite", "value": "UI Test"}, {"name": "suite", "value": "Test Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "VNNOT02222"}, {"name": "thread", "value": "18072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.ui.test_login"}]}