{"uuid": "96cb5c19-845c-4f80-9844-5d4f6d2c7431", "children": ["164e121f-9303-4d58-b199-672a9c1b3cc6"], "befores": [{"name": "setup_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\Desktop\\ATE-AutomationFW-Selenium-Non_BDD-Python-main\\DemoQABookStore\\testcases\\ui\\conftest.py\", line 22, in setup_driver\n    DriverManager.init_driver(pytest.driver_conf)\n  File \"C:\\Users\\annguyenq\\Desktop\\ATE-AutomationFW-Selenium-Non_BDD-Python-main\\DemoQABookStore\\core\\driver\\driver_manager.py\", line 16, in init_driver\n    cls.driver = driver_mapping[config.driver].create_driver(config)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\Desktop\\ATE-AutomationFW-Selenium-Non_BDD-Python-main\\DemoQABookStore\\core\\driver\\driver_types\\chrome_driver.py\", line 9, in create_driver\n    options = webdriver.Chrome('C:/Users/annguyenq/Downloads/chromedriver-win64/chromedriver-win64/chromedriver.exe')\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 47, in __init__\n    self.service.path = DriverFinder.get_path(self.service, self.options)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 44, in get_path\n    raise NoSuchDriverException(f\"Unable to obtain {service.path} using Selenium Manager; {err}\")\n"}, "start": 1702395411961, "stop": 1702395411970}], "start": 1702395411961, "stop": 1702395412125}