{"name": "Test login with invalid accounts", "status": "passed", "parameters": [{"name": "account", "value": "<data_object.account.Account object at 0x00000205A6136A20>"}], "start": 1702398202866, "stop": 1702398204959, "uuid": "b5a7b92b-b347-4ebc-9893-00b5502d2282", "historyId": "0381c65bceed483c6a8808900cd78a24", "testCaseId": "1b1f20a980acb2adddf0d9d9639eb7fe", "fullName": "testcases.ui.test_login#test_login_unsuccessfully_with_valid_account", "labels": [{"name": "parentSuite", "value": "UI Test"}, {"name": "suite", "value": "Test Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "VNNOT02222"}, {"name": "thread", "value": "18072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.ui.test_login"}]}